function [mopaus] = array_multi_beam(mopaus)
% Array control system: Two-beam generation using concentric subapertures
% 31/Aug/2026, Yanwei Huang (h.yanwei@wustl.edu)
%
% Element grouping follows the spiral hardware IDs stored in
% mopaus.element_id, rather than the row-by-row order of bundle_coord:
%   Beam 1: element IDs 1-19 (central 19-core subaperture)
%   Beam 2: element IDs 20-N (outer subaperture)
%
% Parameters
%   mopaus.multi_beam_enable
%   mopaus.source_focus_inner
%   mopaus.source_deflect_azi_inner
%   mopaus.source_deflect_ele_inner
%   mopaus.source_focus_outer
%   mopaus.source_deflect_azi_outer
%   mopaus.source_deflect_ele_outer

if ~isfield(mopaus, 'multi_beam_enable') || mopaus.multi_beam_enable ~= 1
    return;
end

required_fields = { ...
    'element_id', ...
    'bundle_coord', ...
    'element_num', ...
    'speed', ...
    'source_focus_inner', ...
    'source_deflect_azi_inner', ...
    'source_deflect_ele_inner', ...
    'source_focus_outer', ...
    'source_deflect_azi_outer', ...
    'source_deflect_ele_outer'};

for i = 1:numel(required_fields)
    if ~isfield(mopaus, required_fields{i})
        error('Missing required field: mopaus.%s.', required_fields{i});
    end
end

if mopaus.element_num < 20
    error('Multi-beam mode requires at least 20 elements.');
end

validateattributes(mopaus.speed, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'mopaus.speed');

validate_beam_parameters( ...
    mopaus.source_focus_inner, ...
    mopaus.source_deflect_azi_inner, ...
    mopaus.source_deflect_ele_inner, ...
    'inner');

validate_beam_parameters( ...
    mopaus.source_focus_outer, ...
    mopaus.source_deflect_azi_outer, ...
    mopaus.source_deflect_ele_outer, ...
    'outer');

inner_mask = mopaus.element_id >= 1 & mopaus.element_id <= 19;
outer_mask = mopaus.element_id >= 20;

if nnz(inner_mask) ~= 19
    error('Element IDs 1-19 could not be mapped to exactly 19 array elements.');
end

if ~any(outer_mask)
    error('No outer elements with element IDs of 20 or greater were found.');
end

% Use the geometric center as a common timing reference for both beams.
% The steering gradients are identical to the original calculation, while
% the group-to-group timing is independent of an arbitrary edge element.
reference_coord = [0, 0];

mopaus.time_delays = zeros(mopaus.element_num, 1);

mopaus.time_delays(inner_mask) = calculate_beam_delays( ...
    mopaus.bundle_coord(inner_mask, :), ...
    reference_coord, ...
    mopaus.source_focus_inner, ...
    mopaus.source_deflect_azi_inner, ...
    mopaus.source_deflect_ele_inner, ...
    mopaus.speed);

mopaus.time_delays(outer_mask) = calculate_beam_delays( ...
    mopaus.bundle_coord(outer_mask, :), ...
    reference_coord, ...
    mopaus.source_focus_outer, ...
    mopaus.source_deflect_azi_outer, ...
    mopaus.source_deflect_ele_outer, ...
    mopaus.speed);

% Store the masks in the natural coordinate order for visualization or
% channel-specific post-processing. The final hardware delays are reshuffled
% later by array_time_digitize using mopaus.order_spi.
mopaus.multi_beam_inner_mask = inner_mask;
mopaus.multi_beam_outer_mask = outer_mask;

end


function time_delays = calculate_beam_delays( ...
    element_coord, reference_coord, source_focus, ...
    source_deflect_azi, source_deflect_ele, speed)

time_delays = zeros(size(element_coord, 1), 1);

% Apply the same spherical focusing law used in
% array_focusing_deflection. A zero focal length produces an unfocused
% subaperture before steering is applied.
if source_focus ~= 0
    radial_distance_squared = element_coord(:, 1).^2 ...
        + element_coord(:, 2).^2;

    time_delays = -(sqrt(radial_distance_squared + source_focus.^2) ...
        - source_focus) ./ speed;
end

% Apply true-time-delay steering using the same Cartesian convention and
% delay gradients as the original MOPAUS beamforming function.
time_delays = time_delays ...
    + (element_coord(:, 1) - reference_coord(1)) ...
        .* sind(source_deflect_azi) ./ speed ...
    + (element_coord(:, 2) - reference_coord(2)) ...
        .* sind(source_deflect_ele) ./ speed;

end


function validate_beam_parameters(source_focus, deflect_azi, deflect_ele, group_name)

validateattributes(source_focus, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'}, ...
    mfilename, ['mopaus.source_focus_' group_name]);

validateattributes(deflect_azi, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', -90, '<=', 90}, ...
    mfilename, ['mopaus.source_deflect_azi_' group_name]);

validateattributes(deflect_ele, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', -90, '<=', 90}, ...
    mfilename, ['mopaus.source_deflect_ele_' group_name]);

end
